[infra-db]
image=fedora:latest
pull=true
root=false
replace=true

# Motores de bases de datos + herramientas geoespaciales
pkg=postgresql-server,postgresql-contrib,postgis,gdal,geos,proj,libpq-devel,mariadb-server,mariadb,redis

# Volúmenes persistentes
volumes=${HOME}/.local/share/dbdata/postgres:/var/lib/pgsql/data:rw,${HOME}/.local/share/dbdata/mysql:/var/lib/mysql:rw,${HOME}/.local/share/dbdata/redis:/var/lib/redis:rw,${HOME}/Projects/dev_containers_manifest/scripts:/scripts:rw
